spring:
  profiles:
    active: local # 기본 활성 프로필을 local로 지정합니다.
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
